-- Generated by Theme Engine - Do not edit manually

hl.config({
    general = {
        col = {
            active_border = {
                colors = { "rgba(88c0d0ff)", "rgba(81a1c1ff)" },
                angle = 45,
            },
            inactive_border = "rgba(4c566acc)",
        },
    },
    decoration = {
        rounding = 10,
    },
})