-- Generated by Theme Engine - Do not edit manually

hl.config({
    general = {
        col = {
            active_border = {
                colors = { "rgba(fe8019ff)", "rgba(d3869bff)" },
                angle = 45,
            },
            inactive_border = "rgba(504945cc)",
        },
    },
    decoration = {
        rounding = 8,
    },
})