-- Generated by Theme Engine - Do not edit manually

hl.config({
    general = {
        col = {
            active_border = {
                colors = { "rgba(7e9cd8ff)", "rgba(957fb8ff)" },
                angle = 45,
            },
            inactive_border = "rgba(54546dcc)",
        },
    },
    decoration = {
        rounding = 14,
    },
})