source = ~/.config/theme-engine/cache/hyprlock/hyprlock.conf

background {
    color = rgb(1e1e2e)
}

label {
    text = $TIME
    font_size = 64

    position = 0, 150
    halign = center
    valign = center
}

input-field {
    size = 250, 50

    position = 0, -50
    halign = center
    valign = center
}

