general {
    # Garante que apenas uma instância do hyprlock seja iniciada
    lock_cmd = pidof hyprlock || hyprlock

    # Bloqueia a sessão antes de suspender
    before_sleep_cmd = loginctl lock-session

    # Liga a tela novamente ao retornar da suspensão
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Após 5 minutos, bloqueia a tela
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# Após 5 minutos e 30 segundos, desliga os monitores
listener {
    timeout = 720
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Após 30 minutos, suspende o computador
listener {
    timeout = 2000
    on-timeout = systemctl suspend
}
