-- Generated by Theme Engine - Do not edit manually

hl.config({
    general = {
        col = {
            active_border = {
                colors = { "rgba(cba6f7ff)", "rgba(f5c2e7ff)" },
                angle = 45,
            },
            inactive_border = "rgba(45475acc)",
        },
    },
    decoration = {
        rounding = 12,
    },
})