[packages]
native = [
    "archlinux-xdg-menu",
    "ark",
    "awww",
    "base",
    "base-devel",
    "breeze",
    "breeze-gtk",
    "breeze5",
    "chezmoi",
    "chromium",
    "cliphist",
    "dolphin",
    "dolphin-plugins",
    "dosfstools",
    "btop",
    "efibootmgr",
    "falkon",
    "fastfetch",
    "fd",
    "ffmpeg",
    "firefox",
    "foot",
    "fzf",
    "git",
    "gnome-keyring",
    "greetd",
    "greetd-tuigreet",
    "grub",
    "gst-libav",
    "gst-plugins-bad",
    "gst-plugins-base",
    "gst-plugins-good",
    "gst-plugins-ugly",
    "gstreamer",
    "htop",
    "hyprcursor",
    "hypridle",
    "hyprland",
    "hyprlock",
    "hyprpaper",
    "hyprpicker",
    "hyprshot",
    "iwd",
    "kde-cli-tools",
    "kio-admin",
    "kitty",
    "lazydocker",
    "lazygit",
    "linux",
    "linux-firmware",
    "linux-headers",
    "mesa-utils",
    "mpv",
    "mtools",
    "nano",
    "neovim",
    "networkmanager",
    "nm-connection-editor",
    "nodejs",
    "noto-fonts",
    "npm",
    "nwg-look",
    "open-vm-tools",
    "opencode",
    "os-prober",
    "papirus-icon-theme",
    "pavucontrol",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "polkit-kde-agent",
    "python",
    "python-pip",
    "python-jinja2",
    "python-pillow",
    "qt5-wayland",
    "qt6-wayland",
    "rofi",
    "starship",
    "swappy",
    "swaync",
    "tmux",
    "tree",
    "tree-sitter-cli",
    "ttf-droid",
    "ttf-jetbrains-mono-nerd",
    "ttf-opensans",
    "ttf-roboto",
    "unzip",
    "waybar",
    "wireplumber",
    "woff2-font-awesome",
    "wtype",
    "xdg-desktop-portal-gtk",
    "xdg-desktop-portal-hyprland",
    "xdg-user-dirs-gtk",
    "yt-dlp",
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting"
]

aur = [
    "goanime",
    "qt5ct-kde",
    "qt6ct-kde",
    "qview",
    "wlogout",
    "yay"
]

flatpak = []
